from __future__ import annotations

import argparse
import importlib.util
import inspect
import sys
import threading
import typing
from collections.abc import Callable
from pathlib import Path

from vesper.commands.utils import (
    APP_ENTRYPOINTS,
    FRAMEWORK_TEMPLATES,
    find_entrypoint,
    read_vesper_toml,
)

_HEADER = """\
// This file is auto-generated by `vesper sync-types`.
// Do not edit manually — re-run `vesper sync-types` to regenerate.

"""

_FOOTER = """\

type VesperArgs<T extends keyof VesperCommands> = VesperCommands[T]["args"];
type VesperResult<T extends keyof VesperCommands> = VesperCommands[T]["result"];

interface VesperSDK {
  invoke<T extends keyof VesperCommands>(
    command: T,
    args?: VesperArgs<T>
  ): Promise<VesperResult<T>>;
  invoke(command: string, args?: Record<string, unknown>): Promise<unknown>;
  on(event: string, handler: (detail: unknown) => void): () => void;
}

declare const vesper: VesperSDK;
"""


# ── Type mapping ──────────────────────────────────────────────────────────────

def _py_to_ts(ann: object) -> str:
    """Convert a Python type annotation to a TypeScript type string."""
    if ann is inspect.Parameter.empty or ann is None:
        return "unknown"
    if ann is type(None):
        return "null"
    if ann is str:
        return "string"
    if ann is int or ann is float:
        return "number"
    if ann is bool:
        return "boolean"
    if ann is dict:
        return "Record<string, unknown>"
    if ann is list:
        return "Array<unknown>"

    origin = typing.get_origin(ann)
    args = typing.get_args(ann)

    if origin is list:
        inner = _py_to_ts(args[0]) if args else "unknown"
        return f"Array<{inner}>"

    if origin is dict:
        val = _py_to_ts(args[1]) if len(args) >= 2 else "unknown"
        return f"Record<string, {val}>"

    # typing.Union[T, None] / Optional[T] / Python 3.10+ T | None
    union_args = _get_union_args(ann)
    if union_args is not None:
        non_none = [a for a in union_args if a is not type(None)]
        has_none = any(a is type(None) for a in union_args)
        parts = [_py_to_ts(a) for a in non_none]
        ts = " | ".join(parts) if parts else "unknown"
        if has_none:
            ts = f"({ts}) | null" if len(parts) > 1 else f"{ts} | null"
        return ts

    return "unknown"


def _get_union_args(ann: object) -> list | None:
    """Return the type arguments if ann is a Union, else None."""
    origin = typing.get_origin(ann)
    if origin is typing.Union:
        return list(typing.get_args(ann))
    # Python 3.10+ X | Y syntax
    if sys.version_info >= (3, 10):
        import types as _types
        if isinstance(ann, _types.UnionType):
            return list(typing.get_args(ann))
    return None


def _return_to_ts(ann: object) -> str:
    """Like _py_to_ts but maps NoneType → void (correct for return types)."""
    if ann is type(None):
        return "void"
    return _py_to_ts(ann)


# ── Command inspection ────────────────────────────────────────────────────────

def _get_hints(fn: Callable) -> dict:
    try:
        return typing.get_type_hints(fn)
    except Exception:
        return getattr(fn, "__annotations__", {})


def _command_args_ts(fn: Callable) -> str:
    """Generate a TypeScript object literal type for the command's parameters."""
    sig = inspect.signature(fn)
    hints = _get_hints(fn)
    parts: list[str] = []

    for param_name, param in sig.parameters.items():
        if param_name == "self":
            continue
        if param.kind in (
            inspect.Parameter.VAR_POSITIONAL,
            inspect.Parameter.VAR_KEYWORD,
        ):
            continue
        ts_type = _py_to_ts(hints.get(param_name, inspect.Parameter.empty))
        optional = param.default is not inspect.Parameter.empty
        key = f"{param_name}?" if optional else param_name
        parts.append(f"{key}: {ts_type}")

    if not parts:
        return "{}"
    return "{ " + "; ".join(parts) + " }"


def _command_result_ts(fn: Callable) -> str:
    hints = _get_hints(fn)
    return _return_to_ts(hints.get("return", inspect.Parameter.empty))


# ── .d.ts generation ──────────────────────────────────────────────────────────

def generate_dts(commands: dict[str, Callable]) -> str:
    lines: list[str] = [_HEADER, "interface VesperCommands {\n"]

    for name in sorted(commands):
        fn = commands[name]
        args = _command_args_ts(fn)
        result = _command_result_ts(fn)
        lines.append(f'  "{name}": {{ args: {args}; result: {result} }};\n')

    lines.append("}\n")
    lines.append(_FOOTER)
    return "".join(lines)


# ── App loading ───────────────────────────────────────────────────────────────

def _import_app(entrypoint: Path, project_dir: Path):
    """
    Import the entrypoint module and return the App instance.

    Times out after 5 s — an unguarded app.run() call would block forever.
    Returns (app_instance, error_message_or_None).
    """
    from vesper.core.app import App

    result: dict = {}
    prev_path = list(sys.path)
    sys.path.insert(0, str(project_dir))

    def _run() -> None:
        try:
            spec = importlib.util.spec_from_file_location(
                "__vesper_sync__", str(entrypoint)
            )
            if spec is None or spec.loader is None:
                result["error"] = f"Cannot load {entrypoint.name}"
                return
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            for obj in vars(mod).values():
                if isinstance(obj, App):
                    result["app"] = obj
                    return
            result["error"] = f"No App instance found in {entrypoint.name}"
        except Exception as exc:  # noqa: BLE001
            result["error"] = str(exc)

    t = threading.Thread(target=_run, daemon=True)
    t.start()
    t.join(timeout=5)
    sys.path[:] = prev_path

    if t.is_alive():
        return None, (
            f"{entrypoint.name} did not finish loading within 5 s.\n"
            "Make sure app.run() is inside `if __name__ == '__main__':`."
        )
    return result.get("app"), result.get("error")


# ── Output path ───────────────────────────────────────────────────────────────

def _output_path(project_dir: Path, template: str) -> Path:
    if template in FRAMEWORK_TEMPLATES:
        out_dir = project_dir / "src" / "types"
        out_dir.mkdir(parents=True, exist_ok=True)
        return out_dir / "vesper.d.ts"
    return project_dir / "frontend" / "vesper.d.ts"


# ── Main ──────────────────────────────────────────────────────────────────────

def sync_types() -> None:
    project_dir = Path.cwd()
    config = read_vesper_toml(project_dir)
    template = config.get("template", "vanilla")

    entrypoint = find_entrypoint(project_dir)
    if entrypoint is None:
        candidates = ", ".join(APP_ENTRYPOINTS)
        print(f"Could not find app entrypoint ({candidates}).")
        raise SystemExit(1)

    print(f"Loading {entrypoint.name}...")
    app, error = _import_app(entrypoint, project_dir)

    if error:
        print(f"Error: {error}")
        raise SystemExit(1)

    user_commands = {
        k: v for k, v in app.registry._commands.items()
        if not k.startswith("vesper:")
    }

    if not user_commands:
        print("No commands registered — nothing to generate.")
        raise SystemExit(0)

    out_path = _output_path(project_dir, template)
    dts = generate_dts(user_commands)
    out_path.write_text(dts, encoding="utf-8")

    count = len(app.registry._commands)
    noun = "command" if count == 1 else "commands"
    print(f"Generated {out_path.relative_to(project_dir)} ({count} {noun})")


# ── CLI ───────────────────────────────────────────────────────────────────────

def add_sync_types_parser(subparsers: argparse._SubParsersAction) -> None:
    subparsers.add_parser(
        "sync-types",
        help="Generate TypeScript type definitions from registered Python commands.",
    )


def handle_sync_types(args: argparse.Namespace) -> bool:
    if args.command == "sync-types":
        sync_types()
        return True
    return False
